trigger:
  branches:
    include:
    - 'develop'
    - 'main'
    - 'release'
  paths:
    include:
    - QuizTowerPlatform.Bff/**
    exclude:
    - QuizTowerPlatform.Api/**
    - QuizTowerPlatform.ClientApp/**
    - README.md
    - docs/*

pool: Default

variables:
  buildConfiguration: 'release'
  BuildPlatform: 'any cpu'
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
  buildArtifactName: 'gitlab_drop$(Build.BuildId)_$(Build.SourceBranchName)'
  pipelineStartDate: $[format('{0:yyyy}.{0:M}.{0:d}', pipeline.startTime)]
  pipelineStartTime: $[format('{0:H}.{0:m}.{0:s}', pipeline.startTime)]
  solution: 'QuizTowerPlatform.Bff/**/*.csproj'
  MIGRATION: 'true'

jobs:
- job: Build_CI
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '6.11.x'
      
  - task: DotNetCoreCLI@2
    displayName: "Restore"
    inputs:
      command: restore
      projects: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: build
      projects: '$(solution)' 
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: "Test"
    inputs:
      command: test
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'

  - task: FileTransform@1
    displayName: "Transform web.Release.config"
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)/QuizTowerPlatform.Bff'
      enableXmlTransform: true

  - task: DeleteFiles@1
    displayName: "Delete web.Release.config after transformation"
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/QuizTowerPlatform.Bff'
      Contents: '**/web.Release.config'

  - task: CmdLine@2
    displayName: "Overwrite appsettings Bff (Backend for Frontend)"
    inputs:
      workingDirectory: $(Build.SourcesDirectory)/QuizTowerPlatform.Bff
      script: "move appsettings.Release.json appsettings.json"

  - task: DeleteFiles@1
    displayName: "Delete all development appsettings"
    inputs:
      SourceFolder:
      Contents: '**/appsettings.*.json'

  - task: DotNetCoreCLI@2
    displayName: "Publish BFF"
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'QuizTowerPlatform.Bff/QuizTowerPlatform.Bff.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: CopyFiles@2
    displayName: 'Copy Files to provisioning'
    inputs:
      SourceFolder: provisioning
      TargetFolder: '$(build.artifactstagingdirectory)\provisioning'

  - task: PublishBuildArtifacts@1
    displayName: "Upload Artifacts"
    condition: succeeded()
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(buildArtifactName)'