trigger:
  branches:
    include:
    - 'develop'
    - 'main'
    - 'release'
  paths:
    exclude:
    - azure-pipelines-api.yml
    - azure-pipelines-bff.yml
    - QuizTowerPlatform.Api/**
    - QuizTowerPlatform.Bff/**
    - README.md
    - docs/*

pool: Default

variables:
  buildConfiguration: 'release'
  BuildPlatform: 'any cpu'
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
  buildArtifactName: 'gitlab_drop$(Build.BuildId)_$(Build.SourceBranchName)'
  pipelineStartDate: $[format('{0:yyyy}.{0:M}.{0:d}', pipeline.startTime)]
  pipelineStartTime: $[format('{0:H}.{0:m}.{0:s}', pipeline.startTime)]

jobs:
- job: Build_Angular_App
  steps:
  - task: Npm@1
    displayName: 'Install npm packages'
    inputs:
      command: 'install'
      workingDir: 'QuizTowerPlatform.ClientApp'

  - task: Npm@1
    displayName: 'Build Angular App'
    inputs:
      command: 'custom'
      customCommand: 'run build -- --configuration production'
      workingDir: 'QuizTowerPlatform.ClientApp'

  - task: Npm@1
    displayName: 'Run Angular Unit Tests'
    inputs:
      command: 'custom'
      customCommand: 'run test -- --watch=false --browsers=ChromeHeadless'
      workingDir: 'QuizTowerPlatform.ClientApp'
      
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Angular Build Artifacts'
    inputs:
      pathtoPublish: 'QuizTowerPlatform.ClientApp/dist'
      artifactName: '$(buildArtifactName)'