trigger:
  branches:
    include:
    - 'develop'
    - 'main'
    - 'release'
  paths:   
    exclude:
    - QuizTowerPlatform.Bff/**
    - QuizTowerPlatform.ClientApp/**    
    - README.md
    - docs/*

pool: Default

# resources:
#   repositories:
#   - repository: DevOps
#     type: git
#     name: DevOps

variables:
  buildConfiguration: 'release'
  BuildPlatform: 'any cpu'
  isPullRequest: $[eq(variables['Build.Reason'], 'PullRequest')]
  buildArtifactName: 'gitlab_drop$(Build.BuildId)_$(Build.SourceBranchName)'
  pipelineStartDate: $[format('{0:yyyy}.{0:M}.{0:d}', pipeline.startTime)]
  pipelineStartTime: $[format('{0:H}.{0:m}.{0:s}', pipeline.startTime)]
  solution: 'QuizTowerPlatform.Api/**/*.csproj' # OR '**/*.sln' # OR # '**/*.csproj'
  MIGRATION: 'true'

jobs:
- job: Build_CI
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: '6.11.x'
      
  - task: DotNetCoreCLI@2
    displayName: "Restore"
    inputs:
      command: restore
      projects: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: build
      projects: '$(solution)' 
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: "Test"
    inputs:
      command: test
      projects: 'QuizTowerPlatform.Api.Test/**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: FileTransform@1
    displayName: "Transform web.Release.config"
    inputs:
      folderPath: '$(System.DefaultWorkingDirectory)/QuizTowerPlatform.Api'
      enableXmlTransform: true

  - task: DeleteFiles@1
    displayName: "Delete web.Release.config after transformation"
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/QuizTowerPlatform.Api'
      Contents: '**/web.Release.config'

  - task: CmdLine@2
    displayName: "Overwrite appsettings BackendApi"
    inputs:
      workingDirectory: $(Build.SourcesDirectory)/QuizTowerPlatform.Api
      script: "move appsettings.Release.json appsettings.json"

  - task: DeleteFiles@1
    displayName: "Delete all development appsettings"
    inputs:
      SourceFolder:
      Contents: '**/appsettings.*.json'

  - task: PowerShell@2
    displayName: 'Set MIGRATION Variable'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "##vso[task.setvariable variable=MIGRATION]true"

  - task: DotNetCoreCLI@2
    displayName: 'Run EF Migrations'
    condition: eq(variables['MIGRATION'], 'true')
    inputs:
      command: 'custom'
      custom: 'ef'
      arguments: 'database update -c ApiDbContext --project QuizTowerPlatform.Data --startup-project QuizTowerPlatform.Api/QuizTowerPlatform.Api.csproj --configuration $(BuildConfiguration)'

  - task: PowerShell@2
    displayName: 'Reset MIGRATION variable to false'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "##vso[task.setvariable variable=MIGRATION]false"

  - task: DotNetCoreCLI@2
    displayName: "Publish API"
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'QuizTowerPlatform.Api/QuizTowerPlatform.Api.csproj'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: CopyFiles@2
    displayName: 'Copy Files to provisioning'
    inputs:
      SourceFolder: provisioning
      TargetFolder: '$(build.artifactstagingdirectory)\provisioning'

  - task: PublishBuildArtifacts@1
    displayName: "Upload Artifacts"
    condition: succeeded()
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(buildArtifactName)'